# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      
      # Check if this version already exists on npm
      - name: Check if version exists on npm
        id: check_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          if npm view "$PACKAGE_NAME@$PACKAGE_VERSION" version 2>/dev/null; then
            echo "version_exists=true" >> $GITHUB_OUTPUT
            echo "Version $PACKAGE_VERSION already exists on npm registry"
          else
            echo "version_exists=false" >> $GITHUB_OUTPUT
            echo "Version $PACKAGE_VERSION does not exist on npm registry"
          fi
        
      # Only publish if version doesn't exist
      - name: Publish to npm
        if: steps.check_version.outputs.version_exists == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          
      # Skip publishing with informative message
      - name: Skip publishing (version exists)
        if: steps.check_version.outputs.version_exists == 'true'
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "✅ Skipping npm publish - version $PACKAGE_VERSION already exists on npm registry"
          echo "This is expected when the package was published manually before the release"
